### ISSUE TITLE
語意不順暢

### ISSUE THREAD

**Issue by ashramwen** [tailwindcss-tw/tailwindcss.com#20]
**Description**
語意不太順暢，且有多餘空白

**Screenshots**
![image](https://user-images.githubusercontent.com/3334950/114299262-df0c0b80-9aec-11eb-8292-a3f381f9a0f0.png)

**Additional context**
CN的翻譯
![image](https://user-images.githubusercontent.com/3334950/114299276-f5b26280-9aec-11eb-9f6c-c62574d539e7.png)

**Comment by huibizhang** [comment]
If you can = 如果你可以
suppress the XXX long enough = 把 XXX 忍住
 to give it a chance = 然後給它一個機會

urge to = 衝動
retch = 作嘔、吐槽

直翻一樣是
如果你可以忍住衝動不吐槽，給它一個機會， ...... 。

意譯的話，重點在於「忍耐，並給它機會」
那麼「吐槽的衝動」其實是非必要的存在。

我想可能改成
「只要你願意耐心的給它一個機會，」
