### ISSUE TITLE
page of word-break.mdx

### ISSUE THREAD

**Issue by yphsiang** [tailwindcss-tw/tailwindcss.com#59]
./src/pages/docs/word-break.mdx

**Comment by YC999333** [comment]
毛哥 出聲一下 大家擔心你

**Comment by yphsiang** [comment]
哎呀！抱歉抱歉，造成大家的困擾了，據我所知，封鎖時間是24小時，我幾年前被鎖過一次，前一陣子屎蛋也說他被鎖了24小時，所以我想應該今晚七八點就會出關了，先謝謝大家的關心，我以後貼圖或貼連結會小心

![Screenshot_20210419-183556](https://user-images.githubusercontent.com/82197109/115223192-1bb7b280-a13e-11eb-810b-b4ee7fbbdb51.jpg)

**Comment by YC999333** [comment]
你現在知道不要跟line一樣id了吧
